Repository ansforge/IG-fhir-repertoire-offre-ressources-sante, pull requests merged in 2024-02, with the labels that each got.

#296 Correction cardinalité PR.name.prefix
  input/fsh/profiles/RORPractitioner.fsh
Labels: invalid

#306 Correction cardinalité Organization.address
  input/fsh/profiles/ROROrganization.fsh
Labels: invalid

#305 Création extension lieu dit
  input/fsh/extensions/AsLieuDit.fsh
  input/fsh/profiles/RORLocation.fsh
  input/fsh/profiles/ROROrganization.fsh
Labels: enhancement

#269 Sd add MS dans les profils ROR
  input/fsh/profiles/RORHealthcareService.fsh
  input/fsh/profiles/RORLocation.fsh
  input/fsh/profiles/RORMeasure.fsh
  input/fsh/profiles/RORMeasureReport.fsh
  input/fsh/profiles/ROROrganization.fsh
  input/fsh/profiles/RORPractitioner.fsh
  input/fsh/profiles/RORPractitionerRole.fsh
  input/fsh/profiles/RORTask.fsh
Labels: enhancement

#271 Sd ref ressources profils
  input/fsh/profiles/RORHealthcareService.fsh
  input/fsh/profiles/RORLocation.fsh
  input/fsh/profiles/RORMeasureReport.fsh
  input/fsh/profiles/RORPractitioner.fsh
  input/fsh/profiles/RORPractitionerRole.fsh
  input/fsh/profiles/RORTask.fsh
Labels: invalid

#282 Scenarios - Modif narratif avec exemples (suite)
  input/pagecontent/annexes.md
  input/pagecontent/specifications_fonctionnelles.md
  input/pagecontent/specifications_techniques_1.md
  input/pagecontent/specifications_techniques_3.md
  input/pagecontent/specifications_techniques_5.md
  input/pagecontent/specifications_techniques_6.md
  input/pagecontent/specifications_techniques_7.md
  sushi-config.yaml
Labels: enhancement

#290 Correction noms Organization
  input/fsh/profiles/ROROrganization.fsh
Labels: invalid

#267 Scenario - Modif narratif avec exemples
  input/pagecontent/specifications_fonctionnelles.md
  input/pagecontent/specifications_techniques_1.md
  input/pagecontent/specifications_techniques_3.md
  input/pagecontent/specifications_techniques_4.md
Labels: enhancement

#277 Modification requêtes union (_filter)
  input/pagecontent/search_param.md
  input/pagecontent/specifications_techniques_1.md
  input/pagecontent/specifications_techniques_3.md
Labels: enhancement

#319 #318 Bed Management
  input/pagecontent/specifications_techniques_10.md
Labels: enhancement, ror-need-implem
